version: '3.8'

services:
  # Main backend API service
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../logs/app:/app/logs
      - ../data:/app/data
    networks:
      - autonomite
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Supabase database
  db:
    image: supabase/postgres:15.1.0.11
    env_file:
      - ../.env.db
    ports:
      - "5432:5432"
    volumes:
      - ../data/db:/var/lib/postgresql/data
    networks:
      - autonomite
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and temporary data
  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    container_name: autonomite-agent-platform_redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    networks:
      - autonomite
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Container for building agent images
  agent-builder:
    build:
      context: ./agent
      dockerfile: Dockerfile
    image: autonomite/livekit-agent:latest
    container_name: autonomite-agent-builder
    command: echo "Agent image built successfully"
    profiles:
      - build

networks:
  autonomite:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  
  autonomite-agents-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
    labels:
      managed_by: "autonomite-saas"

# No local volumes in production - using mounted directories
volumes:
  autonomite-db-data:
  autonomite-redis-data:

networks:
  default:
    name: autonomite-network