"""
External Lore endpoint support — when a user has registered a self-host
URL + Bearer token via the Sidekick Forge admin UI, all reads and writes
for that user's Lore go through HTTP to their self-host server instead of
touching the platform-hosted lore_files tables.

The self-host server (generated by `lore_mcp/selfhost_template/`) exposes
the same `admin-api/*` HTTP routes that hosted lore_mcp does, so this module
is a thin HTTP client over that contract.

A short in-process TTL cache keeps the platform DB lookup out of the hot
path — the cache is flushed whenever the user updates or disables their
endpoint from the admin UI (see invalidate_cache).
"""

from __future__ import annotations

import logging
import os
import time
from typing import Any, Dict, List, Optional, Tuple

import httpx

LOGGER = logging.getLogger("lore_mcp.external")

_CACHE_TTL_SECONDS = 60
_cache: Dict[str, Tuple[Optional[Tuple[str, str]], float]] = {}


def invalidate_cache(user_id: Optional[str] = None) -> None:
    """Flush the cache — call when the admin UI writes a new endpoint row."""
    if user_id is None:
        _cache.clear()
    else:
        _cache.pop(user_id, None)


def get_external_endpoint(user_id: str) -> Optional[Tuple[str, str]]:
    """Returns (base_url, auth_token) for a user's enabled self-host endpoint,
    or None if they don't have one configured. Cached for 60s."""
    now = time.time()
    cached = _cache.get(user_id)
    if cached and (now - cached[1] < _CACHE_TTL_SECONDS):
        return cached[0]

    from auth import _get_platform_client
    client = _get_platform_client()
    if client is None:
        _cache[user_id] = (None, now)
        return None

    try:
        resp = (
            client.table("lore_external_endpoints")
            .select("base_url,auth_token,enabled")
            .eq("user_id", user_id)
            .maybe_single()
            .execute()
        )
    except Exception as exc:
        LOGGER.warning(f"External endpoint lookup failed for {user_id[:8]}: {exc}")
        _cache[user_id] = (None, now)
        return None

    if not resp or not resp.data:
        _cache[user_id] = (None, now)
        return None
    row = resp.data
    if not row.get("enabled"):
        _cache[user_id] = (None, now)
        return None
    base = (row.get("base_url") or "").rstrip("/")
    token = row.get("auth_token") or ""
    if not base or not token:
        _cache[user_id] = (None, now)
        return None
    result = (base, token)
    _cache[user_id] = (result, now)
    return result


# ---------------------------------------------------------------------------
# HTTP helpers — each mirrors one of the storage operations in app.py
# ---------------------------------------------------------------------------

def _headers(token: str) -> Dict[str, str]:
    return {"Authorization": f"Bearer {token}"}


def remote_read_category(base_url: str, token: str, category: str) -> Optional[str]:
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.get(f"{base_url}/admin-api/category/{category}", headers=_headers(token))
            if resp.status_code == 200:
                return (resp.json() or {}).get("content") or ""
            LOGGER.warning(f"remote_read_category({category}) HTTP {resp.status_code}")
    except Exception as exc:
        LOGGER.warning(f"remote_read_category({category}) failed: {exc}")
    return None


def remote_write_category(base_url: str, token: str, category: str, content: str) -> bool:
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.put(
                f"{base_url}/admin-api/category/{category}",
                headers=_headers(token),
                json={"content": content},
            )
            return resp.status_code == 200
    except Exception as exc:
        LOGGER.error(f"remote_write_category({category}) failed: {exc}")
        return False


def remote_read_summary(base_url: str, token: str) -> Optional[str]:
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.get(f"{base_url}/admin-api/summary", headers=_headers(token))
            if resp.status_code == 200:
                return (resp.json() or {}).get("content") or ""
    except Exception as exc:
        LOGGER.warning(f"remote_read_summary failed: {exc}")
    return None


def remote_list_categories(base_url: str, token: str) -> Optional[List[Dict[str, Any]]]:
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.get(f"{base_url}/admin-api/categories", headers=_headers(token))
            if resp.status_code == 200:
                return resp.json() or []
    except Exception as exc:
        LOGGER.warning(f"remote_list_categories failed: {exc}")
    return None


def test_endpoint(base_url: str, token: str) -> Tuple[bool, str]:
    """Used by the admin UI Test button. Returns (ok, message)."""
    base = (base_url or "").rstrip("/")
    if not base:
        return False, "base_url is empty"
    try:
        with httpx.Client(timeout=5.0) as client:
            hz = client.get(f"{base}/healthz")
            if hz.status_code != 200:
                return False, f"healthz returned HTTP {hz.status_code}"
            # Also check auth works by hitting a protected route
            cats = client.get(f"{base}/admin-api/categories", headers=_headers(token))
            if cats.status_code == 401:
                return False, "auth_token rejected (HTTP 401)"
            if cats.status_code != 200:
                return False, f"admin-api/categories returned HTTP {cats.status_code}"
        return True, "ok"
    except httpx.ConnectError as exc:
        return False, f"connection failed: {exc}"
    except Exception as exc:
        return False, f"test failed: {exc}"
